[package]
name = "Tensai"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.6"


[lib]
name = "tensai"
src = "src/lib.rs"


[[test]]
name = "lex_test"
path = "tests/lex_test.rs"

[[test]]
name = "parse_tests"

